CREATE TABLE submissions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL,
  industry VARCHAR(120) NOT NULL,
  project_type VARCHAR(80) NOT NULL,
  project_scale VARCHAR(40) NOT NULL,
  budget_range VARCHAR(40) NOT NULL,
  primary_region VARCHAR(120) NOT NULL,
  active_users VARCHAR(40) NOT NULL,
  traffic_pattern VARCHAR(40) NOT NULL,
  database_needed VARCHAR(10) NOT NULL,
  file_storage_needed VARCHAR(10) NOT NULL,
  ai_requirement VARCHAR(40) NOT NULL,
  microsoft_integration VARCHAR(40) NOT NULL,
  ease_vs_control VARCHAR(40) NOT NULL,
  existing_provider VARCHAR(40) NOT NULL,
  compliance_requirement VARCHAR(40) NOT NULL,
  support_requirement VARCHAR(40) NOT NULL,
  deployment_preference VARCHAR(40) NOT NULL,
  aws_score INT NOT NULL,
  azure_score INT NOT NULL,
  gcp_score INT NOT NULL,
  final_recommendation VARCHAR(20) NOT NULL,
  confidence_score INT NOT NULL,
  explanation TEXT NOT NULL,
  reasons_json TEXT,
  services_json TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
